# Generated by Django 4.1.2 on 2023-07-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcall', '0002_remove_users_name_users_date_users_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
