# Generated by Django 4.1.2 on 2023-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcall', '0004_activenames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='link',
        ),
        migrations.AddField(
            model_name='users',
            name='isactive',
            field=models.CharField(default='', max_length=100),
        ),
    ]
