# Generated by Django 4.1.2 on 2023-07-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcall', '0007_alter_users_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_name', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('join_time', models.TimeField()),
                ('leave_time', models.TimeField()),
                ('total_time', models.IntegerField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcall.users')),
            ],
        ),
    ]
