# Generated by Django 4.1.2 on 2023-07-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcall', '0008_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='join_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='leave_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='meet_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='history',
            name='total_time',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
