# Generated by Django 4.1.2 on 2023-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcall', '0009_alter_history_join_time_alter_history_leave_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='join_time',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='history',
            name='leave_time',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='history',
            name='meet_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='history',
            name='total_time',
            field=models.IntegerField(default=''),
        ),
    ]
