# Generated by Django 4.1.2 on 2023-07-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcall', '0011_alter_history_join_time_alter_history_leave_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='total_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
